name: babylon-mcp-client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ "20.x" ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: List files
      run: ls -la

    - name: Run CI Script
      run: bash ./run_ci_client.sh
